zookeeper:
  hosts:
    172.105.38.80:
    45.79.125.124:
broker:
  hosts:
    172.105.38.80:
      kafka:
        broker:
          id: 1
    45.79.125.124:
      kafka:
        broker:
          id: 2