all:
  vars:
    security_mode: plaintext
zookeeper:
  hosts:
    172.105.39.74:
broker:
  hosts:
    172.105.39.74:
      kafka:
        broker:
          id: 1
    172.105.38.80:
      kafka:
        broker:
          id: 2