all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    172.105.48.30:  

kafka_broker:
  hosts:
    172.105.48.30:

schema_registry:
  hosts:
    172.105.48.30:
