---
- name: Execuing Common Steps
  hosts: zookeeper:kafka_broker
  tasks:
  - import_role:
      name: confluent.common # required. The name of the role to be executed.

- name: Installing Zookeeper
  hosts: zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Installing Kafka Brokers
  hosts: kafka_broker
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Installing Schema Registry
  hosts: schema_registry
  tasks:
  - import_role:
      name: confluent.schema_register
