---
- name: set schema registry url
  set_fact:
    schema_registry_urls: "{{ schema_registry_urls + 'http://' + item + ':8081,'}}"
  with_items: "{{ server_urls }}"

- name: trim comma trailing schema registry urls
  set_fact:
    schema_registry: "{{ schema_registry_urls[:-1] }}"