---
# defaults file for confluent.zookeeper
zookeeper_peer_port: 2888
zookeeper_leader_port: 3888
zookeeper_current_node_hostname: "{{ inventory_hostname }}"
zookeeper_default_user: cp-kafka
zookeeper_default_group: confluent

zookeeper:
  log_path: /var/log/kafka/
  log_name: zookeeper-server.log
  max_log_files: 10
  log_file_size: 100MB
  config_file: /etc/kafka/zookeeper.properties
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
    admin.enableServer: "false"
    clientPort: 2181