---
- name: Creating Zookeeper dataDir
  file:
    path: "{{zookeeper.properties.dataDir}}"
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"
    state: directory
    mode: 0750

- name: Set Ownership of Data Dir files
  file:
    path: "{{zookeeper.properties.dataDir}}"
    owner: "{{kafka_user}}"
    group: "{{kafka_group}}"
    recurse: true

- name: Create Zookeeper myid file
  template:
      dest: "{{zookeeper.properties.dataDir}}/myid" # required. Location to render the template to on the remote machine.
      src: myid.j2 # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.
      owner: "{{kafka_user}}" # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
      group: "{{kafka_group}}" # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
      mode: 0555 # not required. Mode the file or directory should be. For those used to I(/usr/bin/chmod) remember that modes are actually octal numbers.  You must either add a leading zero so that Ansible's YAML parser knows it is an octal number (like C(0644) or C(01777)) or quote it (like C('644') or C('1777')) so Ansible receives a string and can do its own conversion from string into number.  Giving Ansible a number without following one of these rules will end up with a decimal number which will have unexpected results.  As of version 1.8, the mode may be specified as a symbolic mode (for example, C(u+rwx) or C(u=rw,g=r,o=r)).  As of version 2.6, the mode may also be the special string C(preserve).  C(preserve) means that the file will be given the same permissions as the source file.

- name: Create Zookeeper Configuration File
  template:
      dest: "{{zookeeper.config_file}}"
      src: zookeeper.properties.j2
      owner: "{{kafka_user}}"
      group: "{{kafka_group}}"
      mode: 0400
  register: zookeeper_config
  notify:
    - start zookeeper

- name: start zookeeper
  systemd:
    name: "{{zookeeper_service_name}}"
    state: started